### PR TITLE
Print gitlab password

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by buluma** [comment]
this is a duplication of the verify step which gives you the password after reconfiguration. what your logic?

**Comment by patsevanton** [comment]
current role not print password to std output

```
Starting galaxy role install process
- downloading role 'gitlab', owned by buluma
- downloading role from https://github.com/buluma/ansible-role-gitlab/archive/1.0.15.tar.gz
- extracting buluma.gitlab to /home/user/.ansible/roles/buluma.gitlab
- buluma.gitlab (1.0.15) was installed successfully
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-core in version
 2.15. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Found both group and host with same name: gitlab

PLAY [gitlab] **************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************
Monday 04 April 2022  21:21:32 +0600 (0:00:00.028)       0:00:00.028 **********
ok: [gitlab]

TASK [buluma.gitlab : test if gitlab_version is set correctly] *************************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:05.306)       0:00:05.334 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_release is set correctly] *************************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.024)       0:00:05.358 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_distribution is set correctly] ********************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.021)       0:00:05.380 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_configuration_file is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.021)       0:00:05.401 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_external_url is set correctly] ********************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.420 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_time_zone is set correctly] *****************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.021)       0:00:05.442 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_cleanup_ruby is set correctly] ********************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.023)       0:00:05.466 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_roles is set correctly] ***************************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.021)       0:00:05.488 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if item in gitlab_roles is set correctly] *******************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.508 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_default_theme is set correctly] *******************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.527 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_default_projects_feature_* are set correctly] *****************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.024)       0:00:05.552 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_ldap_enabled is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.027)       0:00:05.579 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_prevent_ldap_sign_in is set correctly] ******************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.599 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_ldap_servers is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.618 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if item in gitlab_rails_ldap_servers is set correctly] ******************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.638 **********
ok: [gitlab -> localhost] => (item=main)
ok: [gitlab -> localhost] => (item=secondary)

TASK [buluma.gitlab : test if group_base item in gitlab_rails_ldap_servers is set correctly] *******************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.070)       0:00:05.709 **********
skipping: [gitlab] => (item=main)
skipping: [gitlab] => (item=secondary)

TASK [buluma.gitlab : test if admin_group item in gitlab_rails_ldap_servers is set correctly] ******************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.023)       0:00:05.732 **********
skipping: [gitlab] => (item=main)
skipping: [gitlab] => (item=secondary)

TASK [buluma.gitlab : test if sync_ssh_keys item in gitlab_rails_ldap_servers is set correctly] ****************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.023)       0:00:05.755 **********
skipping: [gitlab] => (item=main)
skipping: [gitlab] => (item=secondary)

TASK [buluma.gitlab : test if gitlab_rails_manage_backup_path is set correctly] ********************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.023)       0:00:05.779 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_backup_path is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.798 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_backup_gitaly_backup_path is set correctly] *************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.018)       0:00:05.817 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_backup_archive_permissions is set correctly] ************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.837 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_backup_pg_schema is set correctly] **********************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.856 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_backup_keep_time is set correctly] **********************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.020)       0:00:05.876 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if items in gitlab_rails_backup_upload_connection is set correctly] *****************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:05.896 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if aws items in gitlab_rails_backup_upload_connection is set correctly] *************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.015)       0:00:05.912 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if azure items in gitlab_rails_backup_upload_connection is set correctly] ***********************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:05.929 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if azure_storage_domain in gitlab_rails_backup_upload_connection is set correctly] **************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.016)       0:00:05.946 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if google items in gitlab_rails_backup_upload_connection is set correctly] **********************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.016)       0:00:05.962 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_upload_connection is set correctly] **************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:05.980 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_upload_remote_directory is set correctly] ********************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:05.997 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_multipart_chunk_size is set correctly] ***********************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:06.015 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_encryption is set correctly] *********************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:06.032 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_encryption_key is set correctly] *****************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.016)       0:00:06.049 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_upload_storage_options is set correctly] *********************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:06.066 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_backup_storage_class is set correctly] ******************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.016)       0:00:06.082 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_env is set correctly] ***********************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.016)       0:00:06.099 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_smtp_enable is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.017)       0:00:06.117 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_address is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.022)       0:00:06.140 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_port is set correctly] *****************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.021)       0:00:06.161 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_user_name is set correctly] ************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.022)       0:00:06.183 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_password is set correctly] *************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.020)       0:00:06.204 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_domain is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.019)       0:00:06.224 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_authentication is set correctly] *******************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.020)       0:00:06.244 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_enable_starttls_auto is set correctly] *************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.020)       0:00:06.265 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_tls is set correctly] ******************************************************************************************************************
Monday 04 April 2022  21:21:38 +0600 (0:00:00.020)       0:00:06.285 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_pool is set correctly] *****************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:06.306 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_openssl_verify_mode is set correctly] **************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.325 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_ca_path is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:06.347 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_smtp_ca_file is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:06.367 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_enabled is set correctly] ******************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.022)       0:00:06.390 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_from is set correctly] *********************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.409 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_display_name is set correctly] *************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:06.431 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_reply_to is set correctly] *****************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:06.451 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_subject_suffix is set correctly] ***********************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.471 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_smime_enabled is set correctly] ************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.491 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_smime_key_file is set correctly] ***********************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.511 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_smime_cert_file is set correctly] **********************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.017)       0:00:06.528 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_gitlab_email_smime_ca_certs_file is set correctly] ******************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.018)       0:00:06.546 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_adapter is set correctly] ****************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.017)       0:00:06.564 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_encoding is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.584 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_collation is set correctly] **************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.604 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_database is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.621 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_username is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:06.642 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_password is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.022)       0:00:06.664 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_host is set correctly] *******************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:06.685 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_port is set correctly] *******************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:06.706 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_socket is set correctly] *****************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:06.727 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_sslmode is set correctly] ****************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.017)       0:00:06.745 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_sslcompression is set correctly] *********************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.761 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_sslrootcert is set correctly] ************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.022)       0:00:06.784 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_sslcert is set correctly] ****************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.800 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_sslkey is set correctly] *****************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.018)       0:00:06.819 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_prepared_statements is set correctly] ****************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.017)       0:00:06.836 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_statements_limit is set correctly] *******************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.022)       0:00:06.858 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_rails_db_connect_timeout is set correctly] ********************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:06.880 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_keepalives is set correctly] *************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.896 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_keepalives_idle is set correctly] ********************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.912 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_keepalives_interval is set correctly] ****************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.929 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_keepalives_count is set correctly] *******************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.946 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_tcp_user_timeout is set correctly] *******************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.017)       0:00:06.963 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_rails_db_application_name is set correctly] *******************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:06.980 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_letsencrypt is set correctly] *********************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.019)       0:00:06.999 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_ssl_* are set correctly] **************************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:07.020 **********
skipping: [gitlab]

TASK [buluma.gitlab : test if gitlab_letsencrypt_contact_emails is set correctly] ******************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.018)       0:00:07.038 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_group is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:07.058 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_key_size is set correctly] ************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.023)       0:00:07.082 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_owner is set correctly] ***************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:07.104 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_wwwroot is set correctly] *************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:07.124 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_auto_renew is set correctly] **********************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:07.146 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_auto_renew_hour is set correctly] *****************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.020)       0:00:07.166 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_auto_renew_minute is set correctly] ***************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.023)       0:00:07.190 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypt_auto_renew_day_of_month is set correctly] *********************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.024)       0:00:07.214 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_letsencrypy_auto_renew_log_directory is set correctly] ********************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.021)       0:00:07.235 **********
ok: [gitlab -> localhost]

TASK [buluma.gitlab : test if gitlab_trusted_certs is set correctly] *******************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.023)       0:00:07.259 **********
skipping: [gitlab]

TASK [buluma.gitlab : install requirements] ********************************************************************************************************************************************
Monday 04 April 2022  21:21:39 +0600 (0:00:00.016)       0:00:07.276 **********
changed: [gitlab]

TASK [buluma.gitlab : install ruby to allow syntax check of gitlab.rb] *****************************************************************************************************************
Monday 04 April 2022  21:22:03 +0600 (0:00:23.543)       0:00:30.820 **********
changed: [gitlab]

TASK [buluma.gitlab : install apt repository key] **************************************************************************************************************************************
Monday 04 April 2022  21:22:11 +0600 (0:00:08.174)       0:00:38.995 **********
changed: [gitlab]

TASK [buluma.gitlab : install apt repository] ******************************************************************************************************************************************
Monday 04 April 2022  21:22:14 +0600 (0:00:02.492)       0:00:41.487 **********
changed: [gitlab]

TASK [buluma.gitlab : install rpm repository key] **************************************************************************************************************************************
Monday 04 April 2022  21:22:28 +0600 (0:00:14.439)       0:00:55.926 **********
skipping: [gitlab]

TASK [buluma.gitlab : install yum/dnf repository] **************************************************************************************************************************************
Monday 04 April 2022  21:22:28 +0600 (0:00:00.013)       0:00:55.940 **********
skipping: [gitlab]

TASK [buluma.gitlab : install gitlab] **************************************************************************************************************************************************
Monday 04 April 2022  21:22:28 +0600 (0:00:00.011)       0:00:55.951 **********
changed: [gitlab]

TASK [buluma.gitlab : make ssl directories] ********************************************************************************************************************************************
Monday 04 April 2022  21:27:51 +0600 (0:05:22.377)       0:06:18.329 **********
skipping: [gitlab]

TASK [buluma.gitlab : place ssl certificate] *******************************************************************************************************************************************
Monday 04 April 2022  21:27:51 +0600 (0:00:00.019)       0:06:18.348 **********
skipping: [gitlab]

TASK [buluma.gitlab : place ssl key] ***************************************************************************************************************************************************
Monday 04 April 2022  21:27:51 +0600 (0:00:00.015)       0:06:18.364 **********
skipping: [gitlab]

TASK [buluma.gitlab : place configuration templated] ***********************************************************************************************************************************
Monday 04 April 2022  21:27:51 +0600 (0:00:00.017)       0:06:18.381 **********
changed: [gitlab]

TASK [buluma.gitlab : make trusted-certs directories] **********************************************************************************************************************************
Monday 04 April 2022  21:27:54 +0600 (0:00:02.934)       0:06:21.315 **********
skipping: [gitlab]

TASK [buluma.gitlab : place trusted certificates] **************************************************************************************************************************************
Monday 04 April 2022  21:27:54 +0600 (0:00:00.018)       0:06:21.333 **********
skipping: [gitlab]

TASK [buluma.gitlab : place configuration static] **************************************************************************************************************************************
Monday 04 April 2022  21:27:54 +0600 (0:00:00.017)       0:06:21.351 **********
skipping: [gitlab]

RUNNING HANDLER [buluma.gitlab : run gitlab-ctl reconfigure] ***************************************************************************************************************************
Monday 04 April 2022  21:27:54 +0600 (0:00:00.019)       0:06:21.370 **********
changed: [gitlab]

RUNNING HANDLER [buluma.gitlab : uninstall ruby] ***************************************************************************************************************************************
Monday 04 April 2022  21:32:37 +0600 (0:04:43.152)       0:11:04.523 **********
changed: [gitlab]

PLAY RECAP *****************************************************************************************************************************************************************************
gitlab                     : ok=67   changed=8    unreachable=0    failed=0    skipped=45   rescued=0    ignored=0

Monday 04 April 2022  21:32:51 +0600 (0:00:13.782)       0:11:18.305 **********
===============================================================================
buluma.gitlab : install gitlab ------------------------------------------------------------------------------------------------------------------------------------------------ 322.38s
buluma.gitlab : run gitlab-ctl reconfigure ------------------------------------------------------------------------------------------------------------------------------------ 283.15s
buluma.gitlab : install requirements ------------------------------------------------------------------------------------------------------------------------------------------- 23.54s
buluma.gitlab : install apt repository ----------------------------------------------------------------------------------------------------------------------------------------- 14.44s
buluma.gitlab : uninstall ruby ------------------------------------------------------------------------------------------------------------------------------------------------- 13.78s
buluma.gitlab : install ruby to allow syntax check of gitlab.rb ----------------------------------------------------------------------------------------------------------------- 8.18s
Gathering Facts ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.31s
buluma.gitlab : place configuration templated ----------------------------------------------------------------------------------------------------------------------------------- 2.93s
buluma.gitlab : install apt repository key -------------------------------------------------------------------------------------------------------------------------------------- 2.49s
buluma.gitlab : test if item in gitlab_rails_ldap_servers is set correctly ------------------------------------------------------------------------------------------------------ 0.07s
buluma.gitlab : test if gitlab_default_projects_feature_* are set correctly ----------------------------------------------------------------------------------------------------- 0.03s
buluma.gitlab : test if gitlab_default_theme is set correctly ------------------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_version is set correctly ------------------------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_letsencrypt_auto_renew_minute is set correctly --------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_rails_time_zone is set correctly ----------------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_letsencrypt_auto_renew_hour is set correctly ----------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if gitlab_letsencrypt_group is set correctly --------------------------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if admin_group item in gitlab_rails_ldap_servers is set correctly ------------------------------------------------------------------------------------------ 0.02s
buluma.gitlab : test if gitlab_letsencrypy_auto_renew_log_directory is set correctly -------------------------------------------------------------------------------------------- 0.02s
buluma.gitlab : test if group_base item in gitlab_rails_ldap_servers is set correctly ------------------------------------------------------------------------------------------- 0.02s
###############
Execution time was 747 s.
Duration: 0 hours 12 minutes 27 seconds
###############

```

Inventory
```
all:
  children:
    gitlab:
      hosts:
        "gitlab":
          ansible_host: "xxxxx"
  vars:
    gitlab_external_url: "https://xxxxx"
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    gitlab_letsencrypt: yes
    gitlab_letsencrypt_contact_emails:
      - you.email@gmail.com
    gitlab_letsencrypt_group: root
    gitlab_letsencrypt_key_size: 2048
    gitlab_letsencrypt_owner: root
    gitlab_letsencrypt_wwwroot: /var/opt/gitlab/nginx/www
    gitlab_letsencrypt_auto_renew: yes
    gitlab_letsencrypt_auto_renew_hour: 0
    gitlab_letsencrypt_auto_renew_minute: nil
    gitlab_letsencrypt_auto_renew_day_of_month: 7
    gitlab_letsencrypy_auto_renew_log_directory: /var/log/gitlab/lets-encrypt
```

Playbook
```
- hosts: gitlab
  become: true
  roles:
    - role: buluma.gitlab
```

**Review by buluma — COMMENTED** [review]
test build

**Comment by buluma** [comment]
this breaks CI pipeline: fatal: 
[gitlab-enterpriselinux-latest]: FAILED! => {"changed": false, "msg": "file not found: /etc/gitlab/initial_root_password"}

**Pull request merged**
